services:
  db:
    image: postgres:16-alpine
    container_name: go-cloud-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    image: go-cloud:1
    container_name: go-cloud-api
    environment:
      APP_READY: "true"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/go_cloud?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
